# Generated by Django 4.1.6 on 2023-02-13 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1917), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Альбомы',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['musician', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Порядковый номер')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня в альбоме',
                'verbose_name_plural': 'Песни в альбомах',
                'ordering': ['album', 'number'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(through='musicians.SongAlbum', to='musicians.album', verbose_name='Альбомы песни'),
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicians.musician', verbose_name='Исполнитель'),
        ),
        migrations.AddConstraint(
            model_name='songalbum',
            constraint=models.UniqueConstraint(fields=('album', 'number'), name='musicians_songalbum_unique_album_number'),
        ),
        migrations.AddConstraint(
            model_name='songalbum',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='musicians_songalbum_unique_album_song'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('musician', 'year'), name='musicians_album_unique_musician_year'),
        ),
    ]
